// Native CustomRole catalog; authorization remains on the server.
export const PROJECT_CUSTOM_ROLE_PERMISSIONS = Object.freeze([
  'jrc_projects_attachment_manage',
  'jrc_projects_board_manage',
  'jrc_projects_budget_manage',
  'jrc_projects_budget_view',
  'jrc_projects_decision_manage',
  'jrc_projects_issue_manage',
  'jrc_projects_member_manage',
  'jrc_projects_milestone_manage',
  'jrc_projects_project_create',
  'jrc_projects_project_delete',
  'jrc_projects_project_transfer',
  'jrc_projects_project_update',
  'jrc_projects_project_view',
  'jrc_projects_report_export',
  'jrc_projects_report_view',
  'jrc_projects_risk_manage',
  'jrc_projects_sprint_manage',
  'jrc_projects_task_create',
  'jrc_projects_task_delete',
  'jrc_projects_task_move',
  'jrc_projects_task_update',
  'jrc_projects_task_view',
  'jrc_projects_template_manage',
  'jrc_projects_time_entry_create',
  'jrc_projects_time_entry_manage',
]);
